server:
  port: 8081
  contextPath: /user-service
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tpns
    username: tpns
    password: tpns
    driver-class-name: org.postgresql.Driver
    
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG